# OPLib 启动配置文件
version: v2

# 统一配置文件路径（只保留固定的配置）
config_files:
  workflow_config: "config/workflow_config.yaml"
  # 删除 sensor_groups 和 process_stages（应该是动态输入，存储在Redis中）

# 启动参数
startup:
  base_dir: "/home/lenovo/tiansuo_oplib"
  debug: true
  host: "0.0.0.0"
  port: 8000
  reload: false
  log_level: "info" #debug, info, warning, error, critical
  auto_kill_on_port_conflict: true # 启动前若端口被占用，是否自动杀掉占用进程

# 系统级超时设置（用于组件初始化时的默认值）
timeouts:
  kafka: 1000
  database: 30
  api: 30
  webhook: 30
  
